(function(g){var window=this;'use strict';var hu_=function(p,y){if(!Number.isFinite(p))return String(p);p=String(p);var O=p.indexOf(".");O===-1&&(O=p.length);var v=p[0]==="-"?"-":"";v&&(p=p.substring(1));return v+(0,g.bKX)("0",Math.max(0,y-O))+p},bUF=function(){return{W:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{W:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},CXS=function(){return{W:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},U:[{W:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},VYY=function(p){typeof p==="number"?(this.date=D5F(p,0,1),$S(this,1)):g.pA(p)?(this.date=D5F(p.getFullYear(),p.getMonth(),p.getDate()),$S(this,p.getDate())):(this.date=new Date(g.E_()),p=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),$S(this,p))},D5F=function(p,y,O){y=new Date(p,y,O);
p>=0&&p<100&&y.setFullYear(y.getFullYear()-1900);return y},$S=function(p,y){p.getDate()!=y&&p.date.setUTCHours(p.date.getUTCHours()+(p.getDate()<y?1:-1))},sG=function(p,y){g.C9.call(this,p,{W:"div",
L:"ytp-reminder-menu",Z:{role:"menu",tabindex:"-1"},U:[{W:"div",L:"ytp-reminder-menu-contents",U:[{W:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.C=y;this.J=[];this.menuPopupRenderer=void 0;this.items=this.Ju("ytp-reminder-menu-items");this.hide()},AcX=function(p){return(p.menuPopupRenderer&&p.menuPopupRenderer.items||[]).reduce(function(y,O){O&&O.menuServiceItemRenderer&&y.push(O.menuServiceItemRenderer);
return y},[])},rs=function(p){g.U.call(this,{W:"div",
U:[{W:"button",qe:["ytp-offline-slate-button","ytp-button"],U:[{W:"div",L:"ytp-offline-slate-button-icon",Qr:"{{icon}}"},{W:"div",L:"ytp-offline-slate-button-text",Qr:"{{text}}"}]}]});this.N=p;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.T=void 0;this.B=this.C=null;(this.G=this.Ju("ytp-offline-slate-button"))&&this.j(this.G,"click",this.Y);this.hide()},yyY=function(p,y,O){!p.toggleButtonRenderer&&y&&y.toggleButtonRenderer?p.toggleButtonRenderer=y.toggleButtonRenderer:
y&&y.toggleButtonRenderer||(p.toggleButtonRenderer=null);
!p.upcomingEventReminderButtonRenderer&&O&&g.F(O,pVe)?p.upcomingEventReminderButtonRenderer=g.F(O,pVe):O&&g.F(O,pVe)||(p.upcomingEventReminderButtonRenderer=null);av(p)},av=function(p){if(p.toggleButtonRenderer){var y=p.toggleButtonRenderer;
if(y.isToggled){var O=y.toggledText?g.rq(y.toggledText):"";p.update({text:O,icon:OjI(y.toggledIcon)})}else O=y.defaultText?g.rq(y.defaultText):"",p.update({text:O,icon:OjI(y.defaultIcon)});p.show()}else p.upcomingEventReminderButtonRenderer?(y=vIL(p))?(O=y.text?g.rq(y.text):"",p.update({text:O,icon:OjI(y.icon)}),p.show()):p.hide():p.hide()},gI6=function(p,y,O){p.B||(p.B=new g.g3(p.N.X().y7));
var v={context:g.uI(p.B.config_||g.Ps())};g.Z2()&&(v.context.clientScreenNonce=g.Z2());v.params=O;g.EK(p.B,y,v,{timeout:5E3,onSuccess:function(){p.upcomingEventReminderButtonRenderer&&p.T&&(p.upcomingEventReminderButtonRenderer.currentState=p.T,p.T=void 0)},
onError:function(){WE$(p)},
onTimeout:function(){WE$(p)}})},WE$=function(p){p.toggleButtonRenderer?(p.toggleButtonRenderer.isToggled=!p.toggleButtonRenderer.isToggled,av(p)):p.upcomingEventReminderButtonRenderer&&(p.T=void 0,av(p))},OjI=function(p){if(!p)return null;
switch(p.iconType){case "NOTIFICATIONS":return bUF();case "NOTIFICATIONS_NONE":return CXS();case "NOTIFICATIONS_ACTIVE":return g.LC();default:return null}},vIL=function(p){if(!p.upcomingEventReminderButtonRenderer)return null;
var y=p.T||p.upcomingEventReminderButtonRenderer.currentState;p=g.c(p.upcomingEventReminderButtonRenderer.states||[]);for(var O=p.next();!O.done;O=p.next())if((O=g.F(O.value,EI_))&&O.state===y&&O.button&&g.F(O.button,g.CR))return g.F(O.button,g.CR);return null},zwe=function(p){g.U.call(this,{W:"div",
L:"ytp-offline-slate",U:[{W:"div",L:"ytp-offline-slate-background"},{W:"div",L:"ytp-offline-slate-bar",U:[{W:"span",L:"ytp-offline-slate-icon",U:[{W:"svg",Z:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},U:[{W:"path",Z:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{W:"circle",Z:{cx:"12",cy:"12",r:"3"}}]}]},{W:"span",L:"ytp-offline-slate-messages",U:[{W:"div",L:"ytp-offline-slate-main-text",Z:{"aria-label":"{{label}}"},Qr:"{{mainText}}"},{W:"div",L:"ytp-offline-slate-subtitle-text",Qr:"{{subtitleText}}"}]},{W:"span",L:"ytp-offline-slate-buttons"}]},{W:"button",qe:["ytp-offline-slate-close-button","ytp-button"],U:[g.Tx()]},{W:"button",qe:["ytp-offline-slate-open-button","ytp-button"],U:[g.xD()]}]});var y=this;this.api=p;this.C=this.T=null;this.background=this.Ju("ytp-offline-slate-background");
this.J=this.Ju("ytp-offline-slate-bar");this.G=new g.WI(function(){g.S1(y.J,"ytp-offline-slate-bar-fade")},15E3);
this.Y=!1;this.B=new g.WI(function(){g.S1(y.element,"ytp-offline-slate-collapsed")},15E3);
g.B(this,this.B);g.B(this,this.G);this.countdownTimer=new g.WI(this.Fp,1E3,this);this.j(p,"presentingplayerstatechange",this.jn);this.j(p,"livestatedata",this.bb);this.j(this.Ju("ytp-offline-slate-close-button"),"click",function(){g.S1(y.element,"ytp-offline-slate-collapsed")});
this.j(this.Ju("ytp-offline-slate-open-button"),"click",function(){g.PI(y.element,"ytp-offline-slate-collapsed")});
this.hide();p=this.getVideoData();p.getPlayerResponse()&&(p=p.getPlayerResponse().playabilityStatus)&&this.bb(p);p=this.api.getPresentingPlayerType()===8&&!this.getVideoData().fR;var O=this.api.getPresentingPlayerType()===8;g.Jg(this.element,"ytp-offline-slate-premiere-trailer",p);g.Jg(this.element,"ytp-offline-slate-hide-background",O)},GE6=function(p,y,O){if(y){var v=y.subtitleText!=null?g.rq(y.subtitleText):"";
O=O?O:y.mainText!=null?g.rq(y.mainText):"";var W,E,z,f;y=(f=(W=y.mainText)==null?void 0:(E=W.accessibility)==null?void 0:(z=E.accessibilityData)==null?void 0:z.label)!=null?f:O;p.update({mainText:O,subtitleText:v,label:y});g.Jg(p.element,"ytp-offline-slate-single-text-line",!v);g.Jg(p.J,"ytp-offline-slate-bar-hidden",!O&&!v)}},kS=function(p,y){var O=(0,g.I)();
this.trigger=p;this.C=y;this.J=O},SkA=function(p){g.Ru.call(this,p);
var y=this;this.Y=!1;this.S=0;this.D=!1;this.T=new g.WI(function(){oIY(y)},0);
this.C=this.heartbeatParams=null;this.B=!1;this.G=new g.I0(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.P2=new g.g3(void 0);this.attestationResponse=Promise.resolve(void 0);this.V=Promise.resolve(void 0);this.utcOffsetMinutes=-(new VYY).getTimezoneOffset();this.J=new g.hz(this);g.B(this,this.T);g.B(this,this.J);fs_(this);nIF(this);this.J.j(p,"heartbeatparams",this.Oa);this.J.j(p,"presentingplayerstatechange",this.pX);this.J.j(p,"videoplayerreset",this.Qj);this.J.j(p,g.Pg("heartbeat"),
this.onCueRangeEnter);this.B&&this.C&&QHS(this,void 0,this.C);var O=new g.Sv(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),v=new g.Sv(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});p.u0([O,v]);qkF(this)},qkF=function(p){var y=p.getVideoData();
!y.K("use_rta_for_player")&&y.iC&&(y=y.botguardData)&&g.VV(y,p.player.X())},NIU=function(p){var y,O;
return g.w(function(v){if(v.T==1)return g.L(v,g.lz0(),2);if(!v.C)return p.sequenceNumber>=3?v.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):v.return(void 0);y=p.getVideoData();O={};return v.return(g.L4R((O.cpn=y.clientPlaybackNonce,O.encryptedVideoId=y.videoId||"",O),1500))})},fs_=function(p){var y=p.getVideoData();
if(y.iC)if(y.K("use_rta_for_player"))p.attestationResponse=NIU(p);else if(y=new g.epR(y),g.bk.isInitialized()||p.sequenceNumber>=3){var O=Promise,v=O.resolve,W=null;if(y.videoData.J7){var E=g.XNQ(y);if(E){W={};var z={};E=E.split("&");E=g.c(E);for(var f=E.next();!f.done;f=E.next())f=f.value.split("="),f.length===2&&(z[f[0]]=f[1]);z.r1a&&(W.webResponse=z.r1a);z.r1c&&(W.error=PHU[Number(z.r1c)]);W.challenge=y.videoData.J7}}p.attestationResponse=v.call(O,W||void 0)}},uYY=function(p){var y=p.getVideoData();
if(!g.to(p.getVideoData())||y.d8)return!1;if(y.D){p=y.D.flavor==="playready"&&y.K("html5_innertube_heartbeats_for_playready");var O=y.D.flavor==="widevine"&&y.K("html5_innertube_heartbeats_for_widevine");y=g.vT(y.D)&&y.K("html5_innertube_heartbeats_for_fairplay");return!(p||O||y)}return!0},Jy$=function(p){if(uYY(p))return!!p.heartbeatParams;
var y=p.getVideoData();return!g.to(p.getVideoData())||y.ZE||y.gF?!!y.heartbeatToken:!1},xS=function(p,y){if(!p.T.isActive()&&p.Y){var O=p.getVideoData();
if(Jy$(p)||O.isLivePlayback){if(y===void 0)if(p.D)if(p.B)y=7500;else{var v;y=((v=p.heartbeatParams)==null?0:v.interval)?p.heartbeatParams.interval*1E3:p.getVideoData().CU||6E4}else y=1E3;p.T.start(y)}}},$3Y=function(p,y,O){y.M3&&(O=g.MJ(O,{internalipoverride:y.M3}));
var v={cpn:y.clientPlaybackNonce};y.contextParams&&(v.context_params=y.contextParams);y.lI&&(v.kpt=y.lI);O=g.MJ(O,v);g.Z_(O,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(W){if(!p.T.isActive()&&TA(p)){p.G.reset();p.sequenceNumber++;W=W.responseText;var E=KES(W);if(E){p.player.g2("onHeartbeat",E);var z=E.status==="ok"?E.stop_heartbeat?2:0:E.status==="stop"?1:E.status==="live_stream_offline"?0:-1}else z=(z=W.match(cyX))?z[1]==="0"?0:1:-1;Rw$(p,void 0,E,W,z)}},
onError:function(W){TA(p)&&t6(p,!0,"net-"+W.status)},
onTimeout:function(){TA(p)&&t6(p,!0,"timeout")},
withCredentials:!0})},oIY=function(p){var y,O;
g.w(function(v){y=p.player.X();O=p.getVideoData();if(!TA(p))return v.return();if(uYY(p))return sHS(p,y,O),v.W2(0);fs_(p);return g.L(v,ryY(p,y,O),0)})},sHS=function(p,y,O){var v;
if((v=p.heartbeatParams)!=null&&v.url){var W=g.MJ(p.heartbeatParams.url,{request_id:g.xZM()});O.Ne&&(W=g.MJ(W,{vvt:O.Ne}),O.mdxEnvironment&&(W=g.MJ(W,{mdx_environment:O.mdxEnvironment})));g.NN(y,O.oauthToken).then(function(E){E&&(W=g.MJ(W,{access_token:E}));$3Y(p,O,W)})}},TA=function(p){var y=p.getVideoData();
return p.player.getPresentingPlayerType()===3||g.C(p.player.getPlayerStateObject(p.getPlayerType()),4)?!1:Jy$(p)||y.isLivePlayback?!0:(YS(p),!1)},ryY=function(p,y,O){var v,W,E,z,f,n,Q,q,S,N,P,u,R,r,x,k,M,l,H,h;
return g.w(function(X){if(X.T==1)return v="player/heartbeat",E={videoId:O.videoId,sequenceNumber:p.sequenceNumber,heartbeatServerData:(W=p.T4)!=null?W:O.heartbeatServerData},p.V=p.attestationResponse,O.iC?g.L(X,p.V,3):X.W2(2);X.T!=2&&(E.attestationResponse=X.C);z=g.S9(O);n=(f=z.client)!=null?f:{};n.utcOffsetMinutes=p.utcOffsetMinutes;E.context=z;E.cpn=O.clientPlaybackNonce;if(Q=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)n.timeZone=Q;q={heartbeatChecks:[]};
if(S=O.getPlayerResponse())O.heartbeatToken&&(E.heartbeatToken=O.heartbeatToken),(N=S.playabilityStatus)&&(P=N.liveStreamability)&&P.liveStreamabilityRenderer&&q.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");O.heartbeatToken&&q.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.w4(y)&&(q.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),u=asX(p),R={},u!==null&&(R.clientPlayerPositionUtcMillis=u),x=(r=p.player.Jb())==null?void 0:g.MM(r),M=((k=x)==null?void 0:k.freePreviewWatchedDuration)||
0,M>0&&(R.freePreviewWatchedDuration={seconds:""+M}),q.unpluggedParams=R);E.heartbeatRequestParams=q;O.isLivePlayback?(l=asX(p),l!==null&&(E.playbackState||(E.playbackState={}),E.playbackState.playbackPosition={utcTimeMillis:l})):y.K("enable_heartbeat_vod_playback_position")&&(H=kEI(p),H!==null&&(E.playbackState||(E.playbackState={}),E.playbackState.playbackPosition={streamTimeMillis:H}));p.player.publish("heartbeatRequest",E);h={timeout:3E4,onSuccess:function(V){if(!p.T.isActive()&&TA(p)){var WR=
p.getVideoData(),O4=WR.iC&&p.V==null,E4;WR.iC=!((E4=V.heartbeatAttestationConfig)==null||!E4.requiresAttestation)||O4;O4=V.playabilityStatus;E4=JSON.stringify(O4)||"{}";V.authenticationMismatch&&p.player.pj("authshear",{});var b=-1;var PR=V.playabilityStatus;PR&&(p.player.g2("onHeartbeat",PR),PR.status==="OK"?b=V.stopHeartbeat?2:0:PR.status==="UNPLAYABLE"?b=1:PR.status==="LIVE_STREAM_OFFLINE"&&(b=0));p.sequenceNumber&&b===-1||p.G.reset();p.sequenceNumber++;V.heartbeatServerData&&(p.T4=V.heartbeatServerData);
WR.rF=V;(PR=V.playerCueRangeSet)&&g.EY(WR,PR);V.playerCueRanges&&V.playerCueRanges.length>0&&(WR.cueRanges=V.playerCueRanges);var xx,U4;((xx=V.progressBarConfig)==null?0:xx.progressBarStartPosition)&&((U4=V.progressBarConfig)==null?0:U4.progressBarEndPosition)&&(WR.progressBarStartPosition=V.progressBarConfig.progressBarStartPosition,WR.progressBarEndPosition=V.progressBarConfig.progressBarEndPosition);WR.compositeLiveIngestionOffsetToken=V.compositeLiveIngestionOffsetToken;V.compositeLiveStatusToken!==
WR.compositeLiveStatusToken&&(WR.compositeLiveStatusToken=V.compositeLiveStatusToken);WR.publish("dataupdated");Rw$(p,V,O4,E4,b)}},
onError:function(V){TA(p)&&t6(p,!0,"net-"+V.status)},
onTimeout:function(){TA(p)&&t6(p,!0,"timeout")}};
g.NN(y,g.by(O)).then(function(V){V&&(h.G2="Bearer "+V);g.EK(p.P2,v,E,h)});
g.cR(X)})},Rw$=function(p,y,O,v,W){W===-1?(O="decode "+g.GP(v,3),t6(p,!1,O)):W===2?(YS(p),p.D=!0):(p.S=0,p.T.stop(),W===1?(p.D=!1,O&&O.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&p.player.oC(!0),W="pe."+(O==null?void 0:O.errorCode)+";ps."+(O==null?void 0:O.status),p.player.W_("heartbeat.stop",2,p.Tx(v),W),g.Pi("heartbeatActionPlayerHalted",x3L(O)),(y==null?0:y.videoTransitionEndpoint)&&O&&(y=y.videoTransitionEndpoint,(v=g.F(y,g.GR))&&TIS(p,v,O,{itct:y==null?void 0:y.clickTrackingParams}))):(p.D=
!0,v=0,p.B&&O&&(v=QHS(p,y,O),p.player.publish("livestatedata",O)),v?xS(p,v):xS(p)))},QHS=function(p,y,O){var v=O.liveStreamability&&O.liveStreamability.liveStreamabilityRenderer,W=!(!v||!(v.switchStreamsImmediately||v.transitionTiming&&v.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
y=t2S(p,y,v);var E=p.getVideoData(),z=p.player.getPlayerStateObject(p.getPlayerType()),f=z.isPlaying()&&!g.mw(E)&&!p.player.isAtLiveHead(p.getPlayerType());if(E.X().j9()){var n,Q=((n=p.player.pg())==null?void 0:n.M9())||{};Q.status=O.status||"";Q.dvr=""+ +f;Q["switch"]=""+ +W;Q.ended=""+ +!(!v||!v.displayEndscreen);p.player.pj("heartbeat",Q)}n=p.player.K("always_cache_redirect_endpoint");if(f&&!W&&!n)return y;Q=v&&v.streamTransitionEndpoint&&g.F(v.streamTransitionEndpoint,g.GR);var q=v&&v.transitionTiming;
if(q==="STREAM_TRANSITION_TIMING_AT_STREAM_END")p.getVideoData().transitionEndpointAtEndOfStream=Q;else if(n&&!Q&&p.getVideoData().transitionEndpointAtEndOfStream)p.getVideoData().transitionEndpointAtEndOfStream=void 0;else if(!n&&Q&&TIS(p,Q,O))return y;if(f&&!W&&n||n&&Q&&(q==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||q==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&TIS(p,Q,O))return y;if(O.status.toUpperCase()==="OK"){W=v&&v.broadcastId;f=p.C&&p.C.liveStreamability&&p.C.liveStreamability.liveStreamabilityRenderer&&
p.C.liveStreamability.liveStreamabilityRenderer.broadcastId;n=W!==f&&W!=null;if(!g.LV(E)||n){var S={video_id:E.videoId};E.Iy&&(S.is_live_destination="1");S.disable_watch_next=!0;S.raw_watch_next_response=E.getWatchNextResponse();S.autonav_state=E.autonavState;S.oauth_token=E.oauthToken;S.DS=E.DS;E.G&&(S.vss_credentials_token=E.G,S.vss_credentials_token_type=E.i_);E.Ne&&(S.vvt=E.Ne);v=void 0;g.LV(E)?n&&(v=new kS("broadcastIdChanged",f+","+W),p.Q3("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",
O)):(W&&(v=new kS("formatsReceived",""+W)),p.Q3("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",O));p.player.loadVideoByPlayerVars(S,void 0,void 0,void 0,v);return y}p.player.kz("heartbeat",p.getPlayerType())}v&&v.displayEndscreen&&(p.offlineSlate?(p=p.offlineSlate,p.Y=!0,p.Pj&&p.api.q7()):z.isBuffering()&&(E=((S=p.player.pg())==null?void 0:S.M9())||{},p.player.pj("hbse",E,!0),p.player.q7(),p.player.g2("onLiveMediaEnded",O)));return y},t2S=function(p,
y,O){return p.player.K("web_player_use_heartbeat_poll_delay_ms")&&(p=Number(y==null?void 0:y.pollDelayMs))?p:(O=Number(O==null?void 0:O.pollDelayMs))?O:0},t6=function(p,y,O){if(!p.T.isActive()){p.T.stop();
p.S++;var v=y?"heartbeat.net":"heartbeat.servererror";var W=p.getVideoData();if(W.bj||y&&!g.to(p.getVideoData())&&!Jy$(p)&&W.isLivePlayback)W=!1;else{var E,z;((z=p.heartbeatParams)==null?0:z.retries)?E=p.heartbeatParams.retries:E=W.qL||5;W=p.S>=E}W?(g.Pi("heartbeatActionPlayerHalted",y?{enforcedPolicyToHaltOnNetworkFailure:!0}:x3L()),(y=p.getVideoData())&&y.isLivePlayback?p.player.W_(v,1,"Reprodu\u00e7\u00e3o de v\u00eddeo interrompida. Tente novamente.",O):p.player.W_(v,1,"Ocorreu um erro ao licenciar este v\u00eddeo.",
O)):(xS(p,p.G.getValue()),g.eB(p.G))}},x3L=function(p){var y={enforcedPolicyToHaltOnNetworkFailure:!1};
p&&(y.serializedServerContext=p.additionalLoggingData);return y},YS=function(p){p.S=0;
p.T.stop();p.D=!1;p.sequenceNumber=0},nIF=function(p){var y=p.getVideoData(),O=p.player.X();
if(y.isLivePlayback)if(g.NF(O.D)){p.B=!0;p.Y=!0;if(!g.d4(O)||g.w4(O))p.offlineSlate=new zwe(p.player),g.B(p,p.offlineSlate),g.IK(p.player,p.offlineSlate.element,4);(y=y.getPlayerResponse())&&y.playabilityStatus&&(p.C=y.playabilityStatus);var v;((v=p.C)==null?void 0:v.status)!=="UNPLAYABLE"&&(p.C?(v=t2S(p,void 0,p.C.liveStreamability&&p.C.liveStreamability.liveStreamabilityRenderer))?xS(p,v):xS(p,7500):xS(p,1E3))}else p.player.W_("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.PX(y.T4,"heartbeat")&&p.player.kz("heartbeat",p.getPlayerType())},TIS=function(p,y,O,v){var W=y&&y.videoId;
return W?(p.player.hc(W,Object.assign({},{autonav:"1"},v||{}),void 0,!0,!0,y,g.by(p.getVideoData())),p.Q3("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",O),!0):!1},asX=function(p){return(p=p.player.getProgressState(p.getPlayerType()).ingestionTime)&&isFinite(p)?""+Math.floor(p*1E3):null},kEI=function(p){return(p=p.player.getCurrentTime(p.getPlayerType()))&&isFinite(p)?""+Math.floor(p*1E3):null},KES=function(p){try{var y=JSON.parse(p);
return y!=null?y:void 0}catch(O){}},Ykh={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
Ykh={ERAS:["a.C.","d.C."],ERANAMES:["antes de Cristo","depois de Cristo"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),STANDALONEMONTHS:"janeiro fevereiro mar\u00e7o abril maio junho julho agosto setembro outubro novembro dezembro".split(" "),SHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),STANDALONESHORTMONTHS:"jan. fev. mar. abr. mai. jun. jul. ago. set. out. nov. dez.".split(" "),
WEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),STANDALONEWEEKDAYS:"domingo segunda-feira ter\u00e7a-feira quarta-feira quinta-feira sexta-feira s\u00e1bado".split(" "),SHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),STANDALONESHORTWEEKDAYS:"dom. seg. ter. qua. qui. sex. s\u00e1b.".split(" "),NARROWWEEKDAYS:"DSTQQSS".split(""),STANDALONENARROWWEEKDAYS:"DSTQQSS".split(""),SHORTQUARTERS:["T1","T2","T3","T4"],QUARTERS:["1\u00ba trimestre",
"2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, d 'de' MMMM 'de' y","d 'de' MMMM 'de' y","d 'de' MMM 'de' y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{1} '\u00e0s' {0}","{1} '\u00e0s' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
var PHU=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],M2h={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.J=VYY.prototype;g.J.Lp=Ykh.FIRSTDAYOFWEEK;g.J.oM=Ykh.FIRSTWEEKCUTOFFDAY;
g.J.clone=function(){var p=new VYY(this.date);p.Lp=this.Lp;p.oM=this.oM;return p};
g.J.getFullYear=function(){return this.date.getFullYear()};
g.J.getYear=function(){return this.getFullYear()};
g.J.getMonth=function(){return this.date.getMonth()};
g.J.getDate=function(){return this.date.getDate()};
g.J.getTime=function(){return this.date.getTime()};
g.J.getDay=function(){return this.date.getDay()};
g.J.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.J.getUTCMonth=function(){return this.date.getUTCMonth()};
g.J.getUTCDate=function(){return this.date.getUTCDate()};
g.J.getUTCDay=function(){return this.date.getDay()};
g.J.getUTCHours=function(){return this.date.getUTCHours()};
g.J.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.J.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.J.set=function(p){this.date=new Date(p.getFullYear(),p.getMonth(),p.getDate())};
g.J.setFullYear=function(p){this.date.setFullYear(p)};
g.J.setYear=function(p){this.setFullYear(p)};
g.J.setMonth=function(p){this.date.setMonth(p)};
g.J.setDate=function(p){this.date.setDate(p)};
g.J.setTime=function(p){this.date.setTime(p)};
g.J.setUTCFullYear=function(p){this.date.setUTCFullYear(p)};
g.J.setUTCMonth=function(p){this.date.setUTCMonth(p)};
g.J.setUTCDate=function(p){this.date.setUTCDate(p)};
g.J.add=function(p){if(p.years||p.months){var y=this.getMonth()+p.months+p.years*12,O=this.getYear()+Math.floor(y/12);y%=12;y<0&&(y+=12);a:{switch(y){case 1:var v=O%4!=0||O%100==0&&O%400!=0?28:29;break a;case 5:case 8:case 10:case 3:v=30;break a}v=31}v=Math.min(v,this.getDate());this.setDate(1);this.setFullYear(O);this.setMonth(y);this.setDate(v)}p.days&&(O=this.getYear(),y=O>=0&&O<=99?-1900:0,p=new Date((new Date(O,this.getMonth(),this.getDate(),12)).getTime()+p.days*864E5),this.setDate(1),this.setFullYear(p.getFullYear()+
y),this.setMonth(p.getMonth()),this.setDate(p.getDate()),$S(this,p.getDate()))};
g.J.equals=function(p){return!(!p||this.getYear()!=p.getYear()||this.getMonth()!=p.getMonth()||this.getDate()!=p.getDate())};
g.J.toString=function(){var p=this.getFullYear(),y=p<0?"-":p>=1E4?"+":"";return[y+hu_(Math.abs(p),y?6:4),hu_(this.getMonth()+1,2),hu_(this.getDate(),2)].join("")+""};
g.J.valueOf=function(){return this.date.valueOf()};var ZjS=new g.L8("addUpcomingEventReminderEndpoint");var LEF=new g.L8("removeUpcomingEventReminderEndpoint");var lsA=new g.L8("updateUpcomingEventReminderButtonStateCommand");var pVe=new g.L8("upcomingEventReminderButtonRenderer"),EI_=new g.L8("upcomingEventReminderButtonStateRenderer");g.K(sG,g.C9);
sG.prototype.updateMenuItems=function(){var p=this,y=AcX(this),O=0;O=0;for(var v={};O<y.length;v={gg:void 0},O++){var W=this.J[O];W||(W=new g.U({W:"div",L:"ytp-reminder-menu-item",Z:{role:"menuitem",tabindex:"0"},U:[{W:"div",L:"ytp-reminder-menu-item-icon",Qr:"{{icon}}"},{W:"div",L:"ytp-reminder-menu-item-label",Qr:"{{text}}"}]}),v.gg=O,W.listen("click",function(z){return function(){var f=z.gg;p.DH();f=AcX(p)[f];p.publish("reminderMenuItemClicked",f.serviceEndpoint||f.command)}}(v)),W.Au(this.items),
this.J[O]=W);
var E=y[O];v=null;switch(E.icon&&E.icon.iconType){case "NOTIFICATIONS":v=bUF();break;case "NOTIFICATIONS_NONE":v=CXS();break;case "NOTIFICATIONS_ACTIVE":v=g.LC()}E=E.text?g.rq(E.text):"";W.update({icon:v,text:E})}for(;O<this.J.length;)this.J.pop().dispose();O===0?this.DH():this.nF(this.C)};
sG.prototype.hide=function(){this.C&&this.C.removeAttribute("aria-haspopup");g.C9.prototype.hide.call(this)};
sG.prototype.show=function(){this.C&&this.C.setAttribute("aria-haspopup","true");g.C9.prototype.show.call(this)};
sG.prototype.mN=function(){g.Jc(this.J);g.C9.prototype.mN.call(this)};g.K(rs,g.U);
rs.prototype.Y=function(){if(this.toggleButtonRenderer){var p=this.toggleButtonRenderer;p.isToggled?this.J(p.toggledServiceEndpoint):this.J(p.defaultServiceEndpoint);p.isToggled=!p.isToggled;av(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.C&&this.C.Pj)this.C.DH();else{var y=vIL(this);y&&this.J(y.serviceEndpoint||y.command);y=((p=g.F(y==null?void 0:y.command,g.xh))==null?void 0:p.commands)||[];a:{p=g.c(y);for(var O=p.next();!O.done;O=p.next()){var v=y=void 0;if(O=(y=g.F(O.value,g.vsU))==
null?void 0:(v=y.popup)==null?void 0:v.menuPopupRenderer){p=O;break a}}p=void 0}this.C||(this.C=new sG(this.N,this.G),this.C.Au(this.element),g.B(this,this.C),this.C.subscribe("reminderMenuItemClicked",this.J,this));y=this.C;y.menuPopupRenderer=p;y.updateMenuItems()}};
rs.prototype.J=function(p){var y=g.F(p,ZjS),O=g.F(p,LEF);if(p&&(y||O)){if(y){var v=y;var W="notification/add_upcoming_event_reminder"}else O&&(v=O,W="notification/remove_upcoming_event_reminder");if(W&&v&&v.params)for(gI6(this,W,v.params),p=g.c(v.commands||[]),y=p.next();!y.done;y=p.next())if((y=y.value)&&g.F(y,lsA)){this.T=g.F(y,lsA).state;av(this);break}}};g.K(zwe,g.U);g.J=zwe.prototype;g.J.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.J.bb=function(p){var y,O,v=p==null?void 0:(y=p.liveStreamability)==null?void 0:(O=y.liveStreamabilityRenderer)==null?void 0:O.offlineSlate;if(v){this.T=p;y=v.liveStreamOfflineSlateRenderer;y.canShowCountdown?this.Fp():GE6(this,y);var W,E,z,f;if(O=p==null?void 0:(W=p.liveStreamability)==null?void 0:(E=W.liveStreamabilityRenderer)==null?void 0:(z=E.offlineSlate)==null?void 0:(f=z.liveStreamOfflineSlateRenderer)==null?void 0:f.thumbnail){W=0;E=null;z=O.thumbnails;for(f=0;f<z.length;f++)z[f].width>
W&&(W=z[f].width||0,E=z[f].url);E&&(this.background.style.backgroundImage="url("+E+")")}else this.background.style.backgroundImage="";y.actionButtons||y.reminderButton?(this.C||(this.C=new rs(this.api),this.C.Au(this.Ju("ytp-offline-slate-buttons")),g.B(this,this.C)),yyY(this.C,y.actionButtons&&y.actionButtons[0],y.reminderButton)):this.C&&yyY(this.C,null,null);this.T=p}else this.T=null;this.jn()};
g.J.jn=function(p){if(this.api.getPresentingPlayerType()===8)var y=!0;else{var O=this.api.getPlayerStateObject(),v=this.getVideoData();y=v.isLivePlayback&&(O.isBuffering()||g.C(O,2)||g.C(O,64));var W=v.autonavState===2&&g.C(O,2);O=O.isPlaying()&&!g.mw(v)&&!this.api.isAtLiveHead(void 0,!0);y=y&&!O&&!W}y&&this.T?this.Pj?(p==null?0:g.aU(p,2))&&!this.getVideoData().fR&&(g.PI(this.element,"ytp-offline-slate-collapsed"),this.B.stop(),g.PI(this.J,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),
this.B.start(),this.api.publish("offlineslatestatechange"),this.Y&&this.api.q7()):this.Pj&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.J.Fp=function(){var p,y,O,v,W=(p=this.T)==null?void 0:(y=p.liveStreamability)==null?void 0:(O=y.liveStreamabilityRenderer)==null?void 0:(v=O.offlineSlate)==null?void 0:v.liveStreamOfflineSlateRenderer;W&&(p=Math.floor(g.E_()/1E3),y=W.canShowCountdown&&Number(W.scheduledStartTime),!y||y<=p?(GE6(this,W),this.countdownTimer.stop()):(GE6(this,W,g.lP(y-p)),g.gb(this.countdownTimer)))};
g.J.mN=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.mN.call(this)};kS.prototype.T=function(p){return this.trigger&&p.trigger?this.trigger===p.trigger&&this.C===p.C:!1};
kS.prototype.isExpired=function(){return(0,g.I)()-this.J>6E4};
kS.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.C};g.K(SkA,g.Ru);g.J=SkA.prototype;g.J.mN=function(){YS(this);this.player.aY("heartbeat");g.Ru.prototype.mN.call(this)};
g.J.onCueRangeEnter=function(){this.Y=!0;xS(this,2E3)};
g.J.Oa=function(p){this.heartbeatParams=p;xS(this,2E3)};
g.J.pX=function(p){var y;this.player.getPresentingPlayerType()!==8&&((y=this.C)==null?void 0:y.status)!=="UNPLAYABLE"&&(g.C(p.state,2)||g.C(p.state,64)?(YS(this),this.B&&(this.Y=!0,xS(this,1E3))):(g.C(p.state,1)||g.C(p.state,8))&&xS(this,2E3))};
g.J.Qj=function(){this.player.getPresentingPlayerType()!==3&&xS(this,2E3)};
g.J.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.J.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.J.Sh=function(p){switch(p){case 4:case 3:return!1}return!0};
g.J.Q3=function(p,y,O){p={trigger:p,reason:y};O&&(p.serializedServerContext=O.additionalLoggingData);g.Pi("heartbeatActionPlayerTransitioned",p)};
g.J.Tx=function(p){var y="LICENSE",O=KES(p);if(O)return O.reason||g.F7[y]||"";if(p=p.match(cyX))if(p=Number(p[1]))y=(y=M2h[p.toString()])?y:"LICENSE";return g.F7[y]||""};
g.J.rH=function(){return!!this.offlineSlate&&this.offlineSlate.Pj};
var cyX=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.c5("heartbeat",SkA);})(_yt_player);
